name: Linux Build
on: push
jobs:
  build:
    name: 'Java 21 | Ubuntu'
    runs-on: 'ubuntu22-8-32'
    if: ${{ github.repository == 'spring-projects/spring-boot' }}
    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: |
            21
            17
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Build
        env:
          CI: 'true'
          GRADLE_ENTERPRISE_URL: 'https://ge.spring.io'
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        run: ./gradlew '-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false' --no-daemon build -PtoolchainVersion=${{ matrix.java.version }} '-Dorg.gradle.java.installations.auto-detect=false' '-Dorg.gradle.java.installations.auto-download=false' '-Dorg.gradle.java.installations.paths=JAVA_HOME_${{ matrix.java.version }}_X64'
      - name: Print JVM thread dumps when cancelled
        uses: ./.github/actions/print-jvm-thread-dumps
        if: cancelled()
